const TrolleyActionTypes = {
  SHOW_MINI_TROLLEY: "SHOW_MINI_TROLLEY",
  ADD_TO_TROLLEY: "ADD_TO_TROLLEY",
  REDUCE_FROM_TROLLEY: "REDUCE_FROM_TROLLEY",
  CLEAR_ITEM_FROM_TROLLEY: "CLEAR_ITEM_FROM_TROLLEY",
};

export default TrolleyActionTypes;
